### ISSUE TITLE
Update ndt library for ndt7 & Locate v2 only

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt7-client-cc#2]
M-Lab will provide a community supported C++ library and client for ndt7. We are starting with logic from https://github.com/measurement-kit/libndt and removing the older protocols and updating to support Locate v2 API.

Steps:

- [x] Fork & detach upstream measurement-kit/libndt
- [x] Remove ndt5 & web100 logic
- [x] Add support for Locate v2 API
- [x] Allow providing API key parameter
- [x] Allow defining custom CLIENT_NAME at build time
- [x] Make wss default & allow static targets
- [x] Rename libndt to libndt7 throughout
- [x] Rename libndt-client.cpp to ndt7-client.cpp & update flags for ndt7 only
- [x] Update single includes with new changes
- [x] Update README
- [x] Update unit testing
- [x] Update LICENSE to Apache 2.0

**Comment by stephen-soltesz** [comment]
FYI: @bassosimone I've added you as a collaborator on this repo. I've added you to this issue for visibility since you've agreed to review PRs. The above list is my first draft of the steps I expect. If you see things missing, please edit the list directly by editing the comment, you should have permission to do so.

**Comment by bassosimone** [comment]
The list of steps sounds good to me! Thank you @stephen-soltesz!

**Comment by stephen-soltesz** [comment]
We will preserve the _WIN32 support for now.
